### ISSUE TITLE
Terminal Font

### ISSUE THREAD

**Issue by durandj** [webBoxio/atom-term2#107]
Is there a way to specify a font/font family for the terminal panes only? I use powerline for my zsh theme and powerline requires a patched font to work properly. No big deal if its not doable for terminal tabs only, just curious.

**Comment by MoOx** [comment]
just add this in your styles.less

```
.term2 .terminal {
  font-size: inherit;
}
```

**Comment by MoOx** [comment]
THis looks even better

```css
.term2 .terminal {
  font-family: Menlo, Monaco, Inconsolata, monospace;
  font-size: inherit;
}

  .term2 .terminal > div {
    height: inherit;
    line-height: inherit;
  }
```

**Comment by durandj** [comment]
That seems to work, thanks!

**Comment by MoOx** [comment]
Kind of tricky since some values are hardcoded https://github.com/webBoxio/atom-term2/blob/87d315461cb81f45a1f62218f7c6b75be5c1b81b/lib/TermView.coffee#L137-L147

I use for now

```css
.term2 .terminal {
  font-family: Menlo, Monaco, Inconsolata, monospace;
  font-size: inherit;
}

  .term2 .terminal > div {
    height: 13px;
    line-height: 13px;
  }
```
